### ISSUE TITLE
JsonFix.cs error: NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by HulkMaker** [InsaneQA/UnityMedievalCityImporter#1]
NullReferenceException: Object reference not set to an instance of an object
Assets.Scripts.Logic.LevelGeneration.JsonFix.FixJson (UnityEngine.TextAsset jsonAsset, System.String path) (at Assets/Scripts/Logic/LevelGeneration/JsonFix.cs:16)
Assets.Scripts.Logic.LevelGeneration.CityGenerator.FixJson () (at Assets/Scripts/Logic/LevelGeneration/CityGenerator.cs:58)
Assets.Scripts.Logic.LevelGeneration.CityGenerator.GenerateCity () (at Assets/Scripts/Logic/LevelGeneration/CityGenerator.cs:28)
CityGeneratorEditor.OnInspectorGUI () (at Assets/Scripts/Logic/LevelGeneration/Editor/CityGeneratorEditor.cs:15)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <6776482ad98c481c9322bc7e45bcbc33>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by InsaneQA** [comment]
Thanks, will take a look

**Comment by HulkMaker** [comment]
> Thanks, will take a look

It's a very nice project, but the issue is still blocking me after several days. Pls help to check.
Great thanks!

**Comment by InsaneQA** [comment]
@HulkMaker Hi, sorry for the delay.
The source of the issue is the JSON format change - the JSON cannot be deserialized properly.
I've asked the creator of the Medieval City Generator about those changes, and he confirmed that JSON is no longer a GeoJson. https://itch.io/t/1014787/have-geojson-export-been-updated
That means I need to re-write a deserializer.
I'll do my best to finish it during the weekend. Rather than that, I'll upload some small changes, e.g. the CityImporter will now have optional borders around buildings.

**Comment by InsaneQA** [comment]
Fixed.
Please use the newest unitypackage / source code.
I removed the GeoJson usage, so you don't need it anymore

**Comment by InsaneQA** [comment]
@HulkMaker If there is something that I've missed - please reopen the issue
